Repository nasa/CS, pull requests merged in 2022-06, with the labels that each got.

#33 Fix #32, Remove CFE_PSP_MemSet and CFE_PSP_MemSet use
  fsw/src/cs_app.c
  fsw/src/cs_table_processing.c
  unit-test/utilities/cs_test_utils.c
Labels: CCB:Approved

#35 Fix #34, Updates CLA information for Apache 2.0
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/Corp_CLA_CS_250.pdf
  docs/Indv_CLA_CS_250.pdf
Labels: docs, CCB:Approved

#30 Fix #29, Added codeql-build.yml
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, dependency

#36 Fix #10 #14, Improve code coverage
  .github/workflows/unit-test-coverage.yml
  fsw/src/cs_app.c
  fsw/src/cs_events.h
  fsw/src/cs_utils.c
  unit-test/cs_app_tests.c
  unit-test/cs_compute_tests.c
Labels: CCB:Approved
